[package]
name = "Killer"
version = "0.1.0"
edition = "2024"

[dependencies]

winapi = { version = "0.3", features = ["winnt", "tlhelp32", "handleapi", "ioapiset", "fileapi", "errhandlingapi"] }
anyhow = "1.0"



